# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure YB (vx company.com)'
    appType: 'functionAppLinux'
    appName: 'fa-isolated-function-demo'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNET|3.1'
